const { GoogleGenerativeAI } = require("@google/generative-ai");

const geminiApiKey = process.env.GEMINI_API_KEY;
if (!geminiApiKey) {
    throw new Error("Missing GEMINI_API_KEY. Please add GEMINI_API_KEY to your .env or environment variables.");
}

const genAI = new GoogleGenerativeAI(geminiApiKey);

const analyzeWithAI = async (repositoryData) => {

    const model = genAI.getGenerativeModel({
        model: "gemini-2.0-flash"
    });

    const prompt = `
Analyze this GitHub repository.

Repository: ${repositoryData.repository}

Primary Language: ${repositoryData.language}

Stars: ${repositoryData.stars}

Forks: ${repositoryData.forks}

Open Issues: ${repositoryData.openIssues}

Provide:
1. Short Summary
2. Code Quality
3. Three Improvement Suggestions
`;

    const result = await model.generateContent(prompt);

    const response = result.response.text();

    return {
        summary: response,
        quality: "Generated by Gemini",
        suggestions: []
    };

};

module.exports = {
    analyzeWithAI
};